import fs from 'node:fs';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
const html=fs.readFileSync('lib/presentation/streamlit/workflow_canvas_frontend/index.html','utf8');
const dom=new JSDOM(html,{runScripts:'dangerously',beforeParse(w){w.ResizeObserver=class{observe(){}};}});
const w=dom.window,d=w.document,events=[];
w.postMessage=(value)=>events.push(value);
Object.defineProperty(d.getElementById('view'),'clientWidth',{value:680});
Object.defineProperty(d.getElementById('view'),'clientHeight',{value:320});
const labels={node_picker:'Go to node',fit:'Fit',focus:'Locate',hint:'Select',lineage:'Dependencies',overview:'3 nodes',reset:'Actual size',zoom_in:'Zoom in',zoom_out:'Zoom out'};
const nodes=[{id:'ingest',label:'Input',x:24,y:100},{id:'sft',label:'SFT <source>',x:294,y:100},{id:'package',label:'Package',x:564,y:100}].map(n=>({...n,status:'pending',subtitle:'Choose model',glyph:'◇'}));
function render(selected){w.dispatchEvent(new w.MessageEvent('message',{source:w,data:{type:'streamlit:render',args:{spec:{nodes,edges:[['ingest','sft'],['sft','package']],selected,width:810,height:310,labels}}}}));}
render('ingest');
assert.equal(d.getElementById('canvas').style.transform,'scale(1)');
assert.equal(d.getElementById('scale').textContent,'100%');
d.getElementById('fit').click();
assert.notEqual(d.getElementById('canvas').style.transform,'scale(1)');
d.getElementById('reset').click();
assert.equal(d.getElementById('canvas').style.transform,'scale(1)');
nodes[1].models=['Generate: writer <source>', 'Review: critic & judge'];
render('sft');
assert.deepEqual([...d.querySelector('[data-node="sft"] .copy').querySelectorAll('small')].map(x=>x.textContent),nodes[1].models);
assert.equal(d.querySelector('[data-node="sft"] source'),null);
assert.ok(d.querySelector('[data-node="sft"]').title.includes('Review: critic & judge'));
render('ingest');
const picker=d.getElementById('node-picker');
assert.equal(picker.getAttribute('aria-label'),'Go to node');
assert.equal(picker.options.length,3);
assert.equal(picker.options[1].textContent,'SFT <source>');
assert.equal(picker.querySelector('source'),null);
picker.value='package';picker.dispatchEvent(new w.Event('change'));
assert.equal(events.at(-1).value.node,'package');
render('package');
assert.equal(picker.value,'package');
assert.equal(d.querySelector('.node.selected').dataset.node,'package');
assert.equal(d.querySelector('path[data-from="sft"]').getAttribute('stroke-width'),'3');
assert.equal(d.querySelector('path[data-from="ingest"]').getAttribute('stroke-width'),'2');
d.querySelector('[data-node="sft"]').click();
assert.equal(events.at(-1).value.node,'sft');
console.log('Canvas navigation and dependency selection passed');
dom.window.close();
