"""Operations required by backend administration, independent of storage and SDKs."""
from __future__ import annotations

from typing import Any, Protocol


class BackendConfigPort(Protocol):
    def read_config(self, filename: str) -> dict[str, Any]: ...
    def write_local(self, config: dict[str, Any]) -> None: ...
    def spent_usd(self) -> float: ...
    def write_budget_reset(self, caller: str, limit: float) -> float | None: ...
    def audit_budget_reset(self, caller: str, previous_spent: float) -> None: ...
    def env_present(self, name: str) -> bool: ...
    def probe(self, name: str, backend: dict[str, Any]) -> dict[str, Any]: ...
    def discover_models(self, name: str, backend: dict[str, Any]) -> dict[str, Any]: ...
    def read_model_cache(self, name: str, backend: dict[str, Any]) -> dict[str, Any]: ...
    def write_model_cache(self, name: str, backend: dict[str, Any], value: dict[str, Any]) -> None: ...
    def model_connection_signature(self, backend: dict[str, Any], model: str = "") -> str: ...
    def probe_model(self, backend: dict[str, Any], model: str, features=None,
                    budget: dict[str, Any] | None = None) -> dict[str, Any]: ...
