"""Ports for human review and release of CPT corpus candidates."""
from __future__ import annotations

from typing import BinaryIO, Protocol


class CorpusReviewDriver(Protocol):
    def reviewable_runs(self) -> list[dict]: ...
    def queue(self, run_id: str, *, offset: int = 0, limit: int = 20,
              decision: str | None = None) -> dict: ...
    def row(self, run_id: str, sample_id: str) -> dict: ...
    def record_decision(self, run_id: str, expected_hash: str, record: dict) -> dict: ...
    def release(self, run_id: str) -> bytes: ...
    def prepare_release(self, run_id: str) -> dict: ...
    def start_release(self, run_id: str) -> dict: ...
    def cancel_release(self, run_id: str) -> dict | None: ...
    def release_job(self, run_id: str) -> dict | None: ...
    def release_archive(self, run_id: str, release_id: str, expected_hash: str) -> BinaryIO: ...
