"""Ports for auditable human review and release of preference pairs."""
from __future__ import annotations

from typing import BinaryIO, Protocol


class PreferenceReviewDriver(Protocol):
    target: str
    def reviewable_runs(self) -> list[dict]: ...
    def queue(self, run_id: str, *, offset: int = 0, limit: int = 20,
              decision: str | None = None) -> dict: ...
    def pair(self, run_id: str, pair_id: str) -> dict: ...
    def record_decision(self, run_id: str, expected_hash: str, record: dict) -> dict: ...
    def release(self, run_id: str) -> bytes: ...
    def prepare_release(self, run_id: str) -> dict: ...
    def release_archive(self, run_id: str, release_id: str, expected_hash: str) -> BinaryIO: ...
