"""Storage boundary for reading samples and writing immutable trainer releases."""
from __future__ import annotations

from pathlib import Path
from typing import Iterable, Iterator, Protocol


class SamplePreviewRows(Protocol):
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> dict: ...
    def __iter__(self) -> Iterator[dict]: ...


class ReleasePort(Protocol):
    def read_samples(self, path: Path) -> list[dict]: ...
    def replayable_samples(self, path: Path) -> Iterable[dict]: ...
    def preview_samples(self, path: Path) -> SamplePreviewRows: ...
    def raw_preview_samples(self, path: Path) -> SamplePreviewRows: ...

    def review_decisions(self, dataset_name: str) -> list[dict]: ...

    def write_release(self, samples: Iterable[dict], fmt: str, parent: Path, quality: dict,
                      *, corpus_path: Path | None, dpo_path: Path | None,
                      tag: str | None, bulk: bool) -> tuple[Path, dict[str, int]]: ...
