"""Ports for review and release of SFT workflow candidates."""
from __future__ import annotations

from typing import Protocol


class SftReviewDriver(Protocol):
    def reviewable_runs(self) -> list[dict]: ...
    def queue(self, run_id: str, *, offset: int = 0, limit: int = 20,
              decision: str | None = None) -> dict: ...
    def row(self, run_id: str, sample_id: str) -> dict: ...
    def record_decision(self, run_id: str, expected_hash: str, record: dict) -> dict: ...
    def release(self, run_id: str) -> bytes: ...
