"""Inward-facing workspace catalog port."""
from __future__ import annotations

from pathlib import Path
from typing import Protocol


class WorkspaceDriver(Protocol):
    @property
    def default_id(self) -> str: ...
    def add_folder(self, path: str | Path) -> str: ...
    def list_workspaces(self) -> list[str]: ...
    def resolve(self, workspace_id: str | None = None) -> str: ...
    def folder(self, workspace_id: str | None = None) -> Path: ...
    def output(self, workspace_id: str | None = None) -> Path: ...
    def label(self, workspace_id: str) -> str: ...
    def dataset_name(self, workspace_id: str) -> str: ...
    def source_files(self, workspace_id: str, limit: int, suffixes: tuple[str, ...] | None) -> list[Path]: ...
