"""Inward-facing port implemented by workflow persistence/model adapters."""
from __future__ import annotations

from typing import Any, Protocol


class WorkflowDriver(Protocol):
    def create(self, **recipe: Any) -> str: ...
    def agent_replay_capabilities(self) -> dict: ...
    def execute(self, run_id: str) -> dict: ...
    def resume(self, run_id: str) -> dict: ...
    def list_runs(self) -> list[dict]: ...
    def task_runs(self) -> list[dict]: ...
    def state(self, run_id: str) -> dict: ...
    def recipe(self, run_id: str) -> dict: ...
    def is_active(self, run_id: str) -> bool: ...
    def cancel(self, run_id: str) -> None: ...
    def artifact_preview(self, run_id: str, target: str, limit: int) -> list[dict]: ...
    def quarantined_inputs(self, run_id: str, limit: int = 100) -> list[dict]: ...
    def bundle(self, run_id: str) -> bytes: ...
    def prepare_bundle(self, run_id: str) -> dict: ...
    def prepared_bundle(self, run_id: str) -> dict | None: ...
    def start_bundle(self, run_id: str) -> dict: ...
    def bundle_job(self, run_id: str) -> dict | None: ...
    def cancel_bundle(self, run_id: str) -> dict | None: ...
    def artifact_file(self, run_id: str, filename: str) -> bytes: ...
    def package_inventory(self, run_id: str) -> dict: ...
    def quality_report(self, run_id: str) -> dict: ...
    def package_contents(self, run_id: str) -> dict: ...
    def artifact_location(self, run_id: str) -> str: ...
    def list_releases(self) -> list[dict]: ...
    def release_file(self, release_id: str, filename: str) -> bytes: ...
    def source_files(self, workspace_id: str, suffixes: frozenset[str], limit: int) -> list[dict]: ...
    def reviewable_artifacts(self) -> list[str]: ...
