"""Inward-facing port implemented by workflow persistence/model adapters."""
from __future__ import annotations

from typing import Any, Protocol


class WorkflowDriver(Protocol):
    def create(self, **recipe: Any) -> str: ...
    def default_sft_output_style(self) -> str: ...
    def agent_replay_capabilities(self) -> dict: ...
    def web_research_capabilities(self) -> dict: ...
    def save_web_research_connection(self, api_key: str) -> dict: ...
    def check_web_research_connection(self) -> str: ...
    def web_research_results(self, run_id: str) -> dict | None: ...
    def check_agent_sandbox(self) -> dict: ...
    def execute(self, run_id: str) -> dict: ...
    def resume(self, run_id: str) -> dict: ...
    def list_runs(self) -> list[dict]: ...
    def task_runs(self) -> list[dict]: ...
    def state(self, run_id: str) -> dict: ...
    def read_streams(self, run_id: str, *, stage: str | None = None) -> list[dict]: ...
    def read_stream_delta(self, run_id: str, request_id: str, *, offset: int = 0,
                          limit_bytes: int = 65536, stage: str | None = None) -> dict: ...
    def recipe(self, run_id: str) -> dict: ...
    def is_active(self, run_id: str) -> bool: ...
    def cancel(self, run_id: str) -> None: ...
    def artifact_preview(self, run_id: str, target: str, limit: int, offset: int = 0) -> list[dict]: ...
    def quarantined_inputs(self, run_id: str, limit: int = 100) -> list[dict]: ...
    def bundle(self, run_id: str) -> bytes: ...
    def prepare_bundle(self, run_id: str) -> dict: ...
    def prepared_bundle(self, run_id: str) -> dict | None: ...
    def start_bundle(self, run_id: str) -> dict: ...
    def bundle_job(self, run_id: str) -> dict | None: ...
    def cancel_bundle(self, run_id: str) -> dict | None: ...
    def artifact_file(self, run_id: str, filename: str) -> bytes: ...
    def package_inventory(self, run_id: str) -> dict: ...
    def quality_report(self, run_id: str) -> dict: ...
    def package_contents(self, run_id: str) -> dict: ...
    def artifact_location(self, run_id: str) -> str: ...
    def list_releases(self) -> list[dict]: ...
    def release_file(self, release_id: str, filename: str) -> bytes: ...
    def source_files(self, workspace_id: str, suffixes: frozenset[str], limit: int) -> list[dict]: ...
    def reviewable_artifacts(self) -> list[str]: ...
    def agent_review_queue(self, run_id: str, *, kind: str, offset: int,
                           limit: int, decision: str | None) -> dict: ...
    def agent_review_decide(self, run_id: str, candidate_id: str, **decision: Any) -> dict: ...
